<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-09-08">

<title>Tutorial on Electronic Health Records Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter2.html" rel="next">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Tutorial on Electronic Health Records Data</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tutorial on Electronic Health Records Data</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Ontology and Unified Medical Language System (UMLS)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ontology-and-unified-medical-language-system-umls" id="toc-ontology-and-unified-medical-language-system-umls" class="nav-link active" data-scroll-target="#ontology-and-unified-medical-language-system-umls"> <span class="header-section-number">1</span> Ontology and Unified Medical Language System (UMLS)</a>
  <ul class="collapse">
  <li><a href="#sec:1.1" id="toc-sec:1.1" class="nav-link" data-scroll-target="#sec\:1.1"> <span class="header-section-number">1.1</span> Concepts and Relations</a></li>
  <li><a href="#the-necessity-of-a-unified-coding-system" id="toc-the-necessity-of-a-unified-coding-system" class="nav-link" data-scroll-target="#the-necessity-of-a-unified-coding-system"> <span class="header-section-number">1.2</span> The necessity of a unified coding system</a></li>
  <li><a href="#umls-unified-medical-language-system" id="toc-umls-unified-medical-language-system" class="nav-link" data-scroll-target="#umls-unified-medical-language-system"> <span class="header-section-number">1.3</span> UMLS: Unified Medical Language System</a>
  <ul class="collapse">
  <li><a href="#concepts-as-cuis-in-umls" id="toc-concepts-as-cuis-in-umls" class="nav-link" data-scroll-target="#concepts-as-cuis-in-umls"> <span class="header-section-number">1.3.1</span> Concepts as CUIs in UMLS</a></li>
  <li><a href="#different-versions-of-cuis" id="toc-different-versions-of-cuis" class="nav-link" data-scroll-target="#different-versions-of-cuis"> <span class="header-section-number">1.3.2</span> Different versions of CUIs</a></li>
  <li><a href="#relations-in-umls" id="toc-relations-in-umls" class="nav-link" data-scroll-target="#relations-in-umls"> <span class="header-section-number">1.3.3</span> Relations in UMLS</a></li>
  </ul></li>
  <li><a href="#semantic-types-in-umls" id="toc-semantic-types-in-umls" class="nav-link" data-scroll-target="#semantic-types-in-umls"> <span class="header-section-number">1.4</span> Semantic Types in UMLS</a>
  <ul class="collapse">
  <li><a href="#accessing-the-umls" id="toc-accessing-the-umls" class="nav-link" data-scroll-target="#accessing-the-umls"> <span class="header-section-number">1.4.1</span> Accessing the UMLS</a></li>
  </ul></li>
  <li><a href="#concepts-as-codes-in-other-coding-systems" id="toc-concepts-as-codes-in-other-coding-systems" class="nav-link" data-scroll-target="#concepts-as-codes-in-other-coding-systems"> <span class="header-section-number">1.5</span> Concepts as codes in other coding systems</a>
  <ul class="collapse">
  <li><a href="#disease-codes" id="toc-disease-codes" class="nav-link" data-scroll-target="#disease-codes"> <span class="header-section-number">1.5.1</span> Disease codes</a></li>
  <li><a href="#medication-codes" id="toc-medication-codes" class="nav-link" data-scroll-target="#medication-codes"> <span class="header-section-number">1.5.2</span> Medication codes</a></li>
  <li><a href="#procedure-codes" id="toc-procedure-codes" class="nav-link" data-scroll-target="#procedure-codes"> <span class="header-section-number">1.5.3</span> Procedure codes</a></li>
  <li><a href="#laboratory-codes" id="toc-laboratory-codes" class="nav-link" data-scroll-target="#laboratory-codes"> <span class="header-section-number">1.5.4</span> Laboratory codes</a></li>
  </ul></li>
  <li><a href="#aggregation-of-codified-data" id="toc-aggregation-of-codified-data" class="nav-link" data-scroll-target="#aggregation-of-codified-data"> <span class="header-section-number">1.6</span> Aggregation of codified data</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Tutorial on Electronic Health Records Data</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 8, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="ontology-and-unified-medical-language-system-umls" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Ontology and Unified Medical Language System (UMLS)</h1>
<p>Expert knowledge lies at the core of a medical intelligence system. For example, a doctor would know the proper questions to ask a patient if they want to diagnose a rheumatoid arthritis instead of a simple joint injury. This is also what we expect a medical question answering system would be able to do. A common way to equip machines with knowledge is through a knowledge graph composed of concepts and relations. As the opening part of this tutorial, this section introduces fundamental infrastructures in biomedical informatics, i.e., medical concepts and relations between them, along with the available resources.</p>
<section id="sec:1.1" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec:1.1"><span class="header-section-number">1.1</span> Concepts and Relations</h2>
<p>For beginners in biomedical informatics, it is important to figure out the meaning of <em>concept</em> and <em>relation</em>. Let’s look at an example in our daily life. One day one of your friend feels ill and goes to see a doctor. They say <em>I have a stomachache! It’s killing me!</em> Then, the doctor tries to comfort them by saying <em>Your stomach pain will be okay. It looks like a minor stomach disorder.</em> In this case, we got three medical terms: <em>stomachache</em>, <em>stomach pain</em>, and <em>stomach disorder</em>. Moreover, we can find some connections between these terms:</p>
<ol type="1">
<li><p>The terms <em>stomachache</em> and <em>stomach pain</em> refer to the same syndrome (or concept).</p></li>
<li><p>The disease <em>stomach disorder</em> may cause <em>stomachache</em>.</p></li>
</ol>
<p>First, it is obvious that <em>stomachache</em> and <em>stomach pain</em> refer to the same <strong>concept</strong>. Furthermore, with the exception of disease and symptom, every abstract medical entity can be regarded as a concept. They can be procedures, medicine, disorders, mental condition, etc.</p>
<p>Second, there is a <strong>relation</strong> called <em>may_cause</em> between <em>stomach disorder</em> and <em>stomachache</em>. This enables the doctor to make a diagnosis for your friend according to their symptoms and the relation between symptoms and diseases. Besides, there are a lot of other relations between concepts. For instance, Aspirin could relieve physical pain; Hypertensive disease may cause heart failure. These relations are crucial to biomedical informatics because they can reveal to us how medical concepts interact with each other.</p>
</section>
<section id="the-necessity-of-a-unified-coding-system" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-necessity-of-a-unified-coding-system"><span class="header-section-number">1.2</span> The necessity of a unified coding system</h2>
<p>In Section <a href="#sec:1.1" data-reference-type="ref" data-reference="sec:1.1">0.1</a>, we take an example from our daily life to help you understand the meaning of concept and relation. However, biomedical informaticsas an exclusively practical subject, derives its resources from various sources, including but not restricted to textbooks, Wikipedia, and electronic health records (EHR). There are thus great challenges to extracting concepts and relations from the resources, as they not only vary in text style and quality, but also in formats and structures. Therefore, we need a giant <strong>dictionary</strong> to help us deal with these problems.</p>
<p>In the example from the last section, it is obvious that <em>stomachache</em> and <em>stomach pain</em> refer to a same concept. However, if a researcher is dealing with EHRs from 10,000 patients, finding out all the mentions of the same concept will be arduous work because doctors may use various terms to refer to the same disease in their records such as <em>type 2 diabetes</em>, <em>adult-onset diabetes</em>, and <em>diabetes mellitus type 2</em>. Nonetheless, if you have a <strong>dictionary</strong> containing all terms under the same concept, you can find all these mentions easily by direct matching.</p>
<p>Moreover, in the last section, we mentioned that doctors can make diagnoses according to relations between symptoms and diseases. Similarly, If we can gather large quantities of relations between medical concepts, it will be a great help to many fields of biomedical informatics such as auto-diagnosis and relation extraction. Therefore, we hope the <strong>dictionary</strong> also contains the relations between its concepts.</p>
<p>Do we have such a comprehensive dictionary? Of course! In the field of biomedical informatics, we call the giant dictionary <strong>a unified coding system</strong>.</p>
</section>
<section id="umls-unified-medical-language-system" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="umls-unified-medical-language-system"><span class="header-section-number">1.3</span> UMLS: Unified Medical Language System</h2>
<p>UMLS (Unified Medical Language System)&nbsp; is a large language system that unifies medical concept coding, typing, relations between medical concepts, etc. It is not only a standard, but also a large database. In brief, the UMLS is a comprehensive dictionary containing considerable medical terms and relations between them.</p>
<p>You can download data and consult the documentation on the UMLS website <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<section id="concepts-as-cuis-in-umls" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="concepts-as-cuis-in-umls"><span class="header-section-number">1.3.1</span> Concepts as CUIs in UMLS</h3>
<p>It is desirable to have a unique identifier for each concept. In the UMLS, the identifier is called <strong>CUI</strong> (Unique Concept Identifier). The CUI consists of a <em>C</em> followed by several digits such as C0021400 (Influenza).</p>
<p>As we mentioned in the last section, each concept usually has more than one name or aliases. In the UMLS, we refer to these names or aliases as <strong>String</strong>. Thus, we can say that each CUI usually has more than one string.</p>
<p>Among all strings under the same concept, there is always a <strong>preferred</strong> string which is seen as a preferred name of the concept. Researchers usually use preferred names to refer to Concepts because CUIs are difficult to recognize by humans.</p>
<p>All of the CUIs and strings are defined by table <strong>MRCONSO</strong> in the UMLS which contains 4,536,653 concepts with 16,543,671 strings in total. Table&nbsp;<a href="#tab:Identifiers%20in%20UMLS" data-reference-type="ref" data-reference="tab:Identifiers in UMLS">1</a> is an example of a concept with its strings.</p>
<table class="table">
<caption>Table 1: An example of CUIs and strings in UMLS</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 41%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Concept (CUI)</th>
<th>Preferred string of concept</th>
<th>All strings of concept</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C0004238</td>
<td>Atrial Fibrillation</td>
<td><p>Atrial Fibrillation</p>
<p>Atrial Fibrillations</p>
<p>Auricular Fibrillation</p>
<p>Auricular Fibrillations</p></td>
</tr>
</tbody>
</table>
<p>Usually, there are some duplicate strings under the same CUI. Make sure you remove the duplication when constructing your own dictionary.</p>
<p>In addition to CUIs and strings, MRCONSO also provides other information about medical terms, such as language, source vocabularies, types, etc. The MRCONSO is a table of the UMLS, and here&nbsp;<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> is the description of all columns of the table. Here, we only introduce some of them:</p>
<ol type="1">
<li><p><strong>CUI</strong>: Unique identifier for concept</p></li>
<li><p><strong>LAT</strong>: Language of the term</p></li>
<li><p><strong>STR</strong>: String of the term</p></li>
<li><p><strong>SUPPRESS</strong>: Suppressible flag, indicating whether the entry is obsolete</p></li>
</ol>
<p>With the entries in MRCONSO, we can extract all strings under the same CUI easily.</p>
</section>
<section id="different-versions-of-cuis" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="different-versions-of-cuis"><span class="header-section-number">1.3.2</span> Different versions of CUIs</h3>
<p>Over time, CUIs get retired or merged with other CUIs. This happens when</p>
<ol type="1">
<li><p>Two released concepts are found to be synonyms so only one is kept</p></li>
<li><p>The concept is not present in any of the current source vocabularies</p></li>
<li><p>The concept is an acknowledged error in a source vocabulary or determined to be a Metathesaurus production error.</p></li>
</ol>
<p>This information can be tracked using the <strong>MRCUI</strong> table</p>
</section>
<section id="relations-in-umls" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="relations-in-umls"><span class="header-section-number">1.3.3</span> Relations in UMLS</h3>
<p>Relations between concepts in the UMLS are defined in another table called <strong>MRREL</strong>. Each entry of this table provides a relation between a pair of concepts. Let’s look at the example in table&nbsp;<a href="#tab:relations%20example" data-reference-type="ref" data-reference="tab:relations example">2</a>.</p>
<table class="table">
<caption>Table 2: An example of relations in UMLS</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 30%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>CUI1</th>
<th>REL</th>
<th>CUI2</th>
<th>RELA</th>
<th>SUPPRESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C4707509</td>
<td>RO</td>
<td>C0004057</td>
<td>active_ingredient_of</td>
<td>O</td>
</tr>
</tbody>
</table>
<p>Table&nbsp;<a href="#tab:relations%20example" data-reference-type="ref" data-reference="tab:relations example">2</a> presents an entry extracted from the table MRREL (some columns are omitted), which means that <em>C0004057 (Aspirin)</em> is the active ingredient of <em>C4707509 (Aspirin 800mg gastro-resistant oral tablet)</em>. However, the attribute <em>SUPPRESS</em> is <em>O</em>, which means that the entry is probably obsolete. Usually, we only use entries with <em>SUPPRESS</em> = <em>N</em>.</p>
<p>The official document&nbsp;<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> provides the description of all of the columns in MRREL. We only introduce some of them here:</p>
<ol type="1">
<li><p><strong>CUI1/AUI1</strong>: Unique identifier of first concept/atom</p></li>
<li><p><strong>CUI2/AUI2</strong>: Unique identifier of second concept/atom</p></li>
<li><p><strong>REL</strong>: Relationship of second concept or atom to first concept or atom</p></li>
<li><p><strong>RELA</strong>: Additional (more specific) relationship label</p></li>
<li><p><strong>SUPPRESS</strong>: Suppressible flag, indicating whether the entry is obsolete</p></li>
</ol>
<p>The column <strong>RELA</strong> is more frequently used than <strong>REL</strong> because RELA provides much more specific information than REL does. REL only has 13 kinds of sketchy relations such as <em>has a narrower relationship</em> and <em>related and possibly synonymous</em>. On the other hand, RELA provides hundreds of relations such as <em>induces</em>, <em>ingredient_of</em> and <em>isa</em> (is a).</p>
</section>
</section>
<section id="semantic-types-in-umls" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="semantic-types-in-umls"><span class="header-section-number">1.4</span> Semantic Types in UMLS</h2>
<p>In the previous section, We discussed concepts (CUIs) and relations provided by the UMLS. The UMLS also provides categories of these concepts and relations between these categories. These categories are called <strong>Semantic Types</strong> and the relations are called <strong>Semantic Relations</strong>. They constitute the <strong>Semantic Network</strong> of the UMLS. The Semantic Network contains 127 semantic types and 54 relationships. Each concept (CUI) may have more than one semantic type.</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 30%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Level 1</th>
<th>Level 2</th>
<th>Level 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>Experimental Model of Disease</td>
</tr>
<tr class="even">
<td></td>
<td>Physiologic Function</td>
<td>Disease or Syndrome</td>
</tr>
<tr class="odd">
<td>Biologic Function</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Cell Function</td>
</tr>
<tr class="odd">
<td></td>
<td>Pathologic Function</td>
<td>Molecular Function</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Organism Function</td>
</tr>
</tbody>
</table>
<p>Table&nbsp;<a href="#tab:semantic%20hierachy" data-reference-type="ref" data-reference="tab:semantic hierachy">3</a> illustrates the Hierarchy of Semantic Types. The semantic type “Biologic Function” has two children, “Physiologic Function” and “Pathologic Function”, and each of these in turn has several children, too. Each child in the hierarchy is linked to its parent by the “isa” link.</p>
<p>The relations between Semantic Types are also hierarchical. They are grouped into five major categories, which are themselves relations: “physically related to”, “spatially related to”, “temporally related to”, “functionally related to”, and “conceptually related to”.</p>
<section id="accessing-the-umls" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="accessing-the-umls"><span class="header-section-number">1.4.1</span> Accessing the UMLS</h3>
<p>Since the UMLS is a typical relational database, it is convenient to access its tables with any programming language such as Python, Java, R, etc. You can consult the official document of Metathesaurus<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> and Semantic Networks<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> to know about the structures of tables and files. Here we provide some demos for accessing UMLS in Python. The package <em>Pandas</em> is needed.</p>
<p>Access and clean the MRCONSO.RRF (it defines all CUIs in the UMLS) in Metathesaurus:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>MRCONSO_PATH <span class="op">=</span> <span class="st">"MRCONSO.RRF"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># columns of MRCONSO</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>column_conso <span class="op">=</span> [’CUI ’,’LAT’,’TS’,’LUI ’,’STT ’,’SUI ’,’ISPREF ’,’AUI’,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>’SAUI’,’SCUI’,’SDUI ’,’SAB’,’TTY ’,’CODE ’,’STR ’,’SRL’,’SUPPRESS ’,’CVF’]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># read MRCONSO</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>conso <span class="op">=</span> pd . read_csv ( MRCONSO_PATH , dtype <span class="op">=</span>’str’, sep<span class="op">=</span>’<span class="op">|</span>’,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> column_conso , usecols <span class="op">=</span> column_conso , index_col <span class="op">=</span> <span class="va">False</span> )</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (’mrconso size :’, conso.shape )</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># delete non - English and empty words</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>conso <span class="op">=</span> conso [( conso [’LAT ’] <span class="op">==</span> ’ENG ’) <span class="op">&amp;</span> (<span class="op">~</span> conso [’STR ’]. isna () )]</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># delete obsolete words</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>conso <span class="op">=</span> conso [ conso [’SUPPRESS ’] <span class="op">==</span> ’N’]</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># ......</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># ......</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># you can do further cleaning with more operations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Access the MRSTY.RRF (it provides Semantic Type assigned to each concept) in Metathesaurus:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>MRSTY_PATH <span class="op">=</span> <span class="st">'2021new/MRSTY.RRF'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># columns of MRSTY </span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>column_sty <span class="op">=</span> [<span class="st">'CUI'</span>, <span class="st">'TUI'</span>, <span class="st">'STN'</span>, <span class="st">'STY'</span>, <span class="st">'ATUI'</span>, <span class="st">'CVF'</span>]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># read MRSTY </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>sty <span class="op">=</span> pd.read_csv(MRSTY, dtype<span class="op">=</span><span class="st">'str'</span>, sep<span class="op">=</span><span class="st">'|'</span>, names<span class="op">=</span>column_sty, usecols<span class="op">=</span>column_sty, index_col<span class="op">=</span><span class="va">False</span>) </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'mrsty size:'</span>, sty.shape)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#keep all entries with CUI in the cleaned MRCONSO </span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>all_cui <span class="op">=</span> <span class="bu">set</span>(conso[<span class="st">'CUI'</span>]) </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>sty <span class="op">=</span> sty[sty[<span class="st">'CUI'</span>].isin(all_cui)] <span class="bu">print</span>(<span class="st">'final sty'</span>, sty.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="concepts-as-codes-in-other-coding-systems" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="concepts-as-codes-in-other-coding-systems"><span class="header-section-number">1.5</span> Concepts as codes in other coding systems</h2>
<p>Apart from CUIs in the UMLS, there are other common coding systems and they each will be introduced in this section. Most of them are specialized coding systems that encode a specific type of concept including diseases, medications, procedures and laboratory codes.</p>
<section id="disease-codes" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="disease-codes"><span class="header-section-number">1.5.1</span> Disease codes</h3>
<p>Disease codes encode certain diseases, symptoms, and phenotypes into a unique code. Typical disease coding systems include ICD (International Classification of Diseases) codes<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, Phecodes<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>, and HPO (Human Phenotype Ontology) codes<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>. People from different countries or different hospitals may use different coding systems for applications includingEHR and insurance.</p>
<p><strong>ICD Codes</strong></p>
<p>The International Classification of Diseases Codes (ICD) is a list of codes for diseases, symptoms, findings, and injuries that is maintained by the World Health Organization (WHO). ICD codes are used to record medical findings in a standardized format in EHR and to track global morbidity and mortality data. Different countries and different hospitals may use different versions of ICD codes. WHO periodically releases new versions of ICD codes, among which ICD-9 and ICD-10 are relevant to EHR data. The United States uses an extended version of ICD called the “clinical modification” (CM), e.g.&nbsp;ICD-9-CM. ICD-10-CM has over five times the number of diagnosis codes as ICD-9-CM.</p>
<p><strong>Phecodes</strong></p>
<p>Closely related to the ICD codes, Phecodes are phenotyping codes that group various ICD codes into useful phenotypes. ICD codes are very detailed codes, which can be manually rolled up to phecodes. Phecodes version 1.2 condenses roughly 15500 ICD-9-CM codes and 90000 ICD-10-CM codes into 1867 phecodes. ICD codes and phecodes create a certain hierarchy<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> from general phenotype to detailed findings. An example of this hierarchy is shown in Figure 1. A complete ICD-Phecodes system includes ICD codes, ICD strings, corresponding phecodes and phenotypes, and corresponding excluded phecodes range and phenotype. Table 4 shows an example of the ICD-Phecodes system.</p>
<table class="table">
<caption>Table 4: An example of ICD-Phecode system</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 35%">
<col style="width: 7%">
<col style="width: 25%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>ICD-9</th>
<th>ICD-9 String</th>
<th>Phecode</th>
<th>Phenotype</th>
<th>Excl Phecodes</th>
<th>Excl Phenotypes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>250</td>
<td>Diabetes mellitus</td>
<td>250</td>
<td>Diabetes mellitus</td>
<td>249-250.99</td>
<td>DIABETES</td>
</tr>
<tr class="even">
<td>250.1</td>
<td>Diabetes with ketoacidosis</td>
<td>250</td>
<td>Diabetes mellitus</td>
<td>249-250.99</td>
<td>DIABETES</td>
</tr>
<tr class="odd">
<td>250.33</td>
<td>Diabetes mellitus with other coma...</td>
<td>250.1</td>
<td>Type 1 diabetes</td>
<td>249-250.99</td>
<td>DIABETES</td>
</tr>
<tr class="even">
<td>250.13</td>
<td>Type I diabetes mellitus [juvenile type]...</td>
<td>250.11</td>
<td>Type 1 diabetes with ketoacidosis</td>
<td>249-250.99</td>
<td>DIABETES</td>
</tr>
</tbody>
</table>
<p>ICD codes are grouped by phecodes and phenotypes. Numbers after the decimal point of phecodes show certain hierarchies of phenotypes. For example, 250—250.1—250.11 represents the hierarchy of Diabetes mellitus—Type 1 diabetes—Type 1 diabetes with ketoacidosis.</p>
<div id="fig:phecode_hier" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/phecode_hierarchy.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">An example of the ICD-Phecode hierarchy. The most general concept (root) is encoded as an integer in the phecode system, e.g.&nbsp;008. The second level is encoded as a decimal with the same integer part as the root and one digit after the decimal point, while the third level has two digits after the decimal point. Each phecode groups a part of ICD codes.</figcaption><p></p>
</figure>
</div>
<p><strong>HPO Codes</strong></p>
<p>The Human Phenotype Ontology (HPO) provides a standardized vocabulary of phenotypic abnormalities encountered in human disease. HPO mainly consists of two parts; ontology and annotations. The ontology contains detailed information of each term, including id, name, definition, and basic properties such as synonyms, “is-a” relations and cross references. Annotations contain phenotype annotations for certain diseases (whether and how certain diseases will show certain phenotypes or features). They are linked with databases like OMIM or DECIPHER . In the annotation file, each line represents a link between a disease entity such as <em>Noonan syndrome</em> and one of the clinical features characteristically seen in that disease. Examples of the ontology system and annonations are shown in Figure <a href="#fig:hpo_annotate_example" data-reference-type="ref" data-reference="fig:hpo_annotate_example">3</a></p>
<p>HPO currently contains over 13,000 terms and over 156,000 annotations to hereditary diseases. Its detailed descriptions of clinical abnormalities and computable disease definitions have made it the standard for deep phenotyping in the field of rare diseases. HPO can also be mapped to other coding systems like phecodes .</p>
<p><img src="images/hpo%20annotation%20example.jpg" id="fig:hpo_annotate_example" class="img-fluid"></p>
<p>UP: An example of HPO annotations for familial autoinlammatory syndrome 2 introduced by hpo. As is shown in (C), one annotation mainly consists of a disease, a phenotype, and its clinical modifiers and courses (sub-ontologies). This example demonstrates that, in a publication on this disease, three of three reported patients were found to have episodic fever with infantile (or earlier) onset that was triggered by exposure to cold. General format of annotations is described in hpo and https://hpo.jax.org/app/help/annotations.</p>
<p>DOWN: An example of HPO ontology in OBO flat file format obtained from hp.obo which shows the properties of phenotype “Urinary urgency”. OWL version of the HPO which contains more definitions like logical difinitions can be found in https://hpo.jax.org/app/download/ontology.</p>
<p><img src="images/hpo%20ontology.png" class="img-fluid"></p>
</section>
<section id="medication-codes" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="medication-codes"><span class="header-section-number">1.5.2</span> Medication codes</h3>
<p>Medication codes encode drug products and their usage into unique codes. Typical medication coding systems include RxNorm<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> and National Drug Code (NDC)<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>. Medication codes are used in billing or EHR.</p>
<p><strong>RxNorm</strong></p>
<p>RxNorm, produced by The National Library of Medicine (NLM), provides normalized names for clinical drugs and links its names to many of the drug vocabularies commonly used in pharmacy management and drug interaction software, including those of First Databank, Micromedex, and Gold Standard Drug Database. RxNorm provides a set of codes (RxCUI) for clinical drugs, which are the combination of active ingredients, dose form, and strength of a drug. For example, the RxCUI for <em>ciprofloxacin 500 mg 24-hour extended-release tablet</em> (the generic name for Cipro XR 500 mg) is RX10359383, regardless of brand or packaging. RxNorm is also a hierarchical code, with relationships like “has_precise_ingredient”, “has_ingredient”, “has_part”, and “consists_of”.</p>
<p>RxNorm can be downloaded directly through <a href="https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html" class="uri">https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html</a>. The RRF files of RxNorm are just like those of UMLS. The file types are listed in Table <a href="#tab:rxnormtype" data-reference-type="ref" data-reference="tab:rxnormtype">4</a> and their formats are presented in <a href="https://www.nlm.nih.gov/research/umls/rxnorm/docs/techdoc.html#s12_0">RxNorm Technical Documentation</a>. RxNorm can be also navigated through <a href="https://mor.nlm.nih.gov/RxNav/">RxNav</a>, which offers a visualized browser for each RxNorm code. Examples of RxNav is shown in Figure <a href="#fig:rxnav" data-reference-type="ref" data-reference="fig:rxnav">4</a>.</p>
<div id="fig:rxnav" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/rxnav.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">An example of RxNav for Ibuprofen. The browser shows properties like ingredients and clinical drug components of Ibuprofen. RxNav provides an interactive tool for RxNorm.</figcaption><p></p>
</figure>
</div>
<div id="tab:rxnormtype">
<table class="table">
<caption>File types of RxNorm.</caption>
<colgroup>
<col style="width: 54%">
<col style="width: 45%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Concepts, Concept Names, and their sources</td>
<td style="text-align: left;">RXNCONSO.RRF</td>
</tr>
<tr class="even">
<td style="text-align: left;">Attributes</td>
<td style="text-align: left;">RXNSAT.RRF, RXNSTY.RRF</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Relationships</td>
<td style="text-align: left;">RXNREL.RRF</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data about RxNorm</td>
<td style="text-align: left;">RXNDOC.RRF, RXNSAB.RRF, RXNCUI.RRF</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Archive Data</td>
<td style="text-align: left;">RXNATOMARCHIVE.RRF</td>
</tr>
<tr class="even">
<td style="text-align: left;">Concept Changes Tracking Data</td>
<td style="text-align: left;">RXNCUICHANGES.RRF</td>
</tr>
</tbody>
</table>
</div>
<p><strong>NDC</strong></p>
<p>The National Drug Code (NDC) is a unique product identifier used in the United States for drugs intended for human use. It’s published by U.S. Food and Drug Administration (FDA). Through NDC, drugs are identified and reported using a unique, three-segment number which serves as the FDA’s identifier for drugs.</p>
<p>The first segment, the labeler code, is 4, 5 or 6 digits long and identifies the labeler such as the drug manufacturer, repackager, or distributer. The second segment, the product code, is 3 or 4 digits long and identifies a specific strength, dosage form, and formulation for a particular firm. The third segment, the package code, is 1 or 2 digits long and identifies package forms and sizes. For example, the product NDC of <em>Ibuprofen</em> produced by Granules India Limited is 62207-0356.</p>
</section>
<section id="procedure-codes" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="procedure-codes"><span class="header-section-number">1.5.3</span> Procedure codes</h3>
<p>Procedure codes are a sub-type of medical classification used to identify specific surgical, medical, or diagnostic procedures. Typical procedure codes include Current Procedural Terminology (CPT) and ICD-10 Procedure Coding System (ICD-10-PCS). Procedure codes are used in billing, EHR, and insurance.</p>
<p><strong>CPT</strong></p>
<p>The Current Procedural Terminology (CPT) code set is a procedural code set developed by the American Medical Association (AMA). The CPT code set describes medical, surgical, and diagnostic procedures for administrative, financial, and analytical purposes. There are three types of CPT codes. Category 1 are 5-digit codes that cover evaluation and management, anesthesiology, surgery, radiology, pathology and laboratory, and medicine. These are the most widely used CPT codes. Category 2 are clinical laboratory services and category 3 are emerging technologies, services and procedures. Examples of CPT codes are listed in Table <a href="#tab:cpt" data-reference-type="ref" data-reference="tab:cpt">5</a>.</p>
<div id="tab:cpt">
<table class="table">
<caption>Examples of CPT codes.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">CPT</th>
<th style="text-align: left;">Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3120F</td>
<td style="text-align: left;">12-LEAD ECG PERFORMED</td>
</tr>
<tr class="even">
<td style="text-align: left;">4030F</td>
<td style="text-align: left;">LONG-TERM OXYGEN THERAPY PRESCRIBED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0575F</td>
<td style="text-align: left;">HIV RNA CONTROL PLAN OF CARE DOCD</td>
</tr>
</tbody>
</table>
</div>
<p><strong>ICD-10-PCS</strong></p>
<p>The ICD-10 Procedure Coding System (ICD-10-PCS) is an international system of medical classification used for procedural coding. ICD-9-CM contains a procedure classification while ICD-10-CM does not, so ICD-10-PCS is the procedure classification for ICD-10. Each ICD-10-PCS code consists of seven alphanumeric characters. The first character is the ‘section’. The second through seventh characters mean different things in each section. Each character can be any of 34 possible values the ten digits 0-9 and the 24 letters A-H, J-N and P-Z may be used in each character. The letters O and I are excluded to avoid confusion with the numbers 0 and 1. There are no decimals in ICD-10-PCS. Of the 72,081 codes in ICD-10-PCS, 62,022 are in the first section, “Medical and surgical”. Detailed descriptions of the sections can be found in <a href="https://en.wikipedia.org/wiki/ICD-10_Procedure_Coding_System#Section_structure">Wiki</a>. For example, 07Q70ZZ is the code for <em>Repair Thorax Lymphatic, Open Approach</em>.</p>
</section>
<section id="laboratory-codes" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="laboratory-codes"><span class="header-section-number">1.5.4</span> Laboratory codes</h3>
<p>Laboratory codes identify medical laboratory observations. The Logical Observation Identifier Names and Codes (LOINC) is the most widely-used laboratory codes.</p>
<p><strong>LOINC</strong></p>
<p>The Logical Observation Identifier Names and Codes (LOINC) database provides a universal code system for reporting laboratory and other clinical observations. The database currently has over 71,000 observation terms. A LOINC term includes 6 parts: component, kind of property, time aspect, system, type of scale, and type of method. An example of LOINC term is shown in Table <a href="#tab:Example%20of%20clinical%20LOINC%20terms%20and%20names" data-reference-type="ref" data-reference="tab:Example of clinical LOINC terms and names ">6</a>.</p>
<p>LOINC has a hierarchical structure. It can be represented as a tree, where each leaf is the LOINC term and the parents are LOINC parts (whose codes are started with LP, e.g.&nbsp;LP14559-6 stands for <em>Bacteria</em>). A visualization of such structure can be browsed in <a href="https://loinc.org/tree/" class="uri">https://loinc.org/tree/</a>.</p>
<table class="table">
<caption>Table 7: Example of LOINC term body weight</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>Component</th>
<th>Property</th>
<th>Time Aspect</th>
<th>System</th>
<th>Scale</th>
<th>Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>29463-7</td>
<td>Body weight</td>
<td>Mass</td>
<td>Pt</td>
<td>ˆ Patient</td>
<td>Qn</td>
<td></td>
</tr>
</tbody>
</table>
<p>Component indicates what is measured, evaluated, or observed. Property indicates characteristics of what is measured. Time aspect indicates interval of time over which the observation or measurement was made. Pt means point in time. System indicates context or specimen type within which the observation was made, e.g.&nbsp;blood or urine. Scale indicates the scale of measure. Qn means quantitative. Method indicates the procedure used to make the measurement or observation.</p>
</section>
</section>
<section id="aggregation-of-codified-data" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="aggregation-of-codified-data"><span class="header-section-number">1.6</span> Aggregation of codified data</h2>
<p>EHR data typically include four domains of codified data: diagnosis, procedures, lab measurements, and medications. Due to differential coding practices, the same clinical concepts might be represented by distinct clinical codes at different healthcare systems. For example, acute myocardial infarction (MI) of anterolateral wall and acute MI of the inferolateral wall are separate codes that describe the same concept of MI . To reduce ambiguity and alleviate heterogeneity across different healthcare systems, the individual clinical codes are usually rolled to codes representing general concepts. More specifically, ICD codes are often aggregated into PheCodes using the ICD-to-PheCode mapping from PheWAS catalog (<a href="https://phewascatalog.org/phecodes" class="uri">https://phewascatalog.org/phecodes</a>). Procedure codes including CPT-4, HCPCS, ICD-9-PCS, ICD-10-PCS are grouped into clinical classification software (CCS) categories based on the CCS mapping ( <a href="https://www.hcup-us.ahrq.gov/toolssoftware/ccs_svcsproc/ccssvcproc.jsp" class="uri">https://www.hcup-us.ahrq.gov/toolssoftware/ccs_svcsproc/ccssvcproc.jsp</a>). Medication codes are often aggregated and rolled up into ingredient level RxNorm codes. Laboratory measurements can be aggregated into LOINC codes and further grouped into higher level LOINC Parts codes (LP codes) to reflect broader laboratory code concepts by leveraging the LOINC Multiaxial Hierarchy.</p>


</section>
</section>
<section class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1" role="doc-endnote"><p>The website of the UMLS is <a href="https://www.nlm.nih.gov/research/umls/index.html" class="uri">https://www.nlm.nih.gov/research/umls/index.html</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p><a href="https://www.ncbi.nlm.nih.gov/books/NBK9685/table/ch03.T.concept_names_and_sources_file_mr/" class="uri">https://www.ncbi.nlm.nih.gov/books/NBK9685/table/ch03.T.concept_names_and_sources_file_mr/</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p><a href="https://www.ncbi.nlm.nih.gov/books/NBK9685/table/ch03.T.related_concepts_file_mrrel_rrf/" class="uri">https://www.ncbi.nlm.nih.gov/books/NBK9685/table/ch03.T.related_concepts_file_mrrel_rrf/</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p><a href="https://www.ncbi.nlm.nih.gov/books/NBK9685/" class="uri">https://www.ncbi.nlm.nih.gov/books/NBK9685/</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5" role="doc-endnote"><p><a href="https://www.ncbi.nlm.nih.gov/books/NBK9679/" class="uri">https://www.ncbi.nlm.nih.gov/books/NBK9679/</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6" role="doc-endnote"><p><a href="https://www.who.int/standards/classifications/classification-of-diseases" class="uri">https://www.who.int/standards/classifications/classification-of-diseases</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7" role="doc-endnote"><p><a href="https://phewascatalog.org/phecodes" class="uri">https://phewascatalog.org/phecodes</a><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8" role="doc-endnote"><p><a href="https://hpo.jax.org/app/" class="uri">https://hpo.jax.org/app/</a><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9" role="doc-endnote"><p>The figure is obtained from a visualization tool for ICD codes and phecodes. <a href="https://hmsrsc.aws.hms.harvard.edu/content/89/" class="uri">https://hmsrsc.aws.hms.harvard.edu/content/89/</a><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10" role="doc-endnote"><p>https://www.nlm.nih.gov/research/umls/rxnorm/index.html<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11" role="doc-endnote"><p>https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter2.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 2</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>